### ISSUE TITLE
Address sub-menu styling when in mobile view port

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#118]
The sub-menu on the hiring process is not collapsing when screen is going to mobile view port

URL: https://federalist-a2423046-fe43-4e75-a2ef-2651e5e123ca.sites.pages.cloud.gov/preview/gsa-tts/tts.gsa.gov/echo-summer20203/join/hiring-process/

Example of rendering
![image](https://github.com/user-attachments/assets/91d876de-aa39-480c-b705-a146add801ae)

**Comment by wesley-dean-gsa** [comment]
The current version of USWDS is [3.8.1](https://designsystem.digital.gov/download/) which was released on May 31, 2024.

The pinned version of USWDS is [3.0.2](https://github.com/GSA-TTS/tts.gsa.gov/blob/main/package.json#L52) which was release on June 17, 2022.

Maybe bumping the version of USWDS might help?

**Comment by wesley-dean-gsa** [comment]
![Screenshot_20240802_143014](https://github.com/user-attachments/assets/8776fb02-26ad-45c8-8ca5-28bb52c726c9)

This is a screenshot showing the rendering using an updated USWDS version.

**Comment by wesley-dean-gsa** [comment]
![Screenshot_20240802_145440](https://github.com/user-attachments/assets/9761ae78-c435-4223-b752-dc3f9654054d)

another screenshot showing further down the page

**Comment by debjudy** [comment]
Will have Ximena give this a look to let us know how much effort fixing looks to be.  

See thread for details on ideas https://gsa-tts.slack.com/archives/C07BMFCK4NS/p1722622798580819

**Comment by wesley-dean-gsa** [comment]
During standup on Monday, August 5th, @katelandisgsa mentioned that we don't want to spend an excessive amount of time on this given that we'll be rebuilding the site before long and the issue will no longer be applicable.  So, the thinking is that we'll explore what would be involved in addressing this now.

**Comment by debjudy** [comment]
Since Ximena will not be rolling onto project for a couple of weeks yet, we are going to roll with the approach as it is and add issue to backlog to make it better once we have more front end expertise available to team.

**Comment by debjudy** [comment]
Closed this issue.  Work will be done under #148
