### ISSUE TITLE
Add repo to Allstar configuration

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#120]
Submit a pull request to add your repository to our Github configuration scanner to the [GSA](https://github.com/GSA/.allstar/blob/main/allstar.yaml) or [GSA-TTS](https://github.com/GSA-TTS/.allstar/blob/main/allstar.yaml) organizations

**Comment by wesley-dean-gsa** [comment]
This will be for the `GSA` repo; just add `tts.gsa.gov` to the `optConfig.optInRepos[]` list on https://github.com/GSA/.allstar/blob/main/allstar.yaml

**Comment by wesley-dean-gsa** [comment]
We noticed that Allstar is actively monitoring our repo as evidenced by #112 being created automatically and then being closed as resolved when we took remediating action.  Therefore, this step may no longer be required and we can close out this ticket.

**Comment by wesley-dean-gsa** [comment]
https://github.com/gsa-tts/.allstar

> AllStar is currently configured to scan all the repositories which it's authorized to access in the corresponding GitHub App, so repo updates require the GSA TTS DevTools team to update those permissions.

point: we don't need to take further action at this time.

**Comment by debjudy** [comment]
No PR needed. Closing issue.
