### ISSUE TITLE
Complete DLP Self-Assessment

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#124]
Complete the [DLP spreadsheet](https://docs.google.com/spreadsheets/d/1ga0n2_DzjKZ8a8D1Pgj7edRHqfLmryxIiwq0JGjJctQ/edit)

The instructions say to make a copy of the spreadsheet.  This *is* the copy.

**Comment by wesley-dean-gsa** [comment]
@katelandisgsa shared an updated DLP spreadsheet; the link in the description of this issue has been updated.

**Comment by wesley-dean-gsa** [comment]
GSA's Digital Strategy (for the Governance sheet) is located here: https://www.gsa.gov/technology/government-it-initiatives/digital-strategy?gsaredirect=digitalstrategy

**Comment by debjudy** [comment]
Team agreed during sprint planning that checklist is in good place and that this body of work is complete.
