### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#132]
In order to maintain a tidy repo, I want to clean up old branches. 

**Acceptance criteria**
- [ ] Old branches removed if appropriate
- [ ] Old branches merged if appropriate

_Notes_
As of end of July 2024, there are 30+ branches in the repo many of which are stale.

**Comment by wesley-dean-gsa** [comment]
20 of those branches are 9 months old.  I vote we send them off to the great bit bucket in the sky just for starters.

Branches off of `main` are supposed to be deleted when PRs are merged automatically, so any branches relating to closed PRs can also go away.

**Comment by wesley-dean-gsa** [comment]
we can go ahead and delete the unmerged and/or stale branches

**Comment by wesley-dean-gsa** [comment]
All of the stale branches were removed.  Then all of the branches associated with PRs that have been merged and/or closed were removed.  There are now 3 branches: main plus the two branches associated with open PRs.  It's as clean as it could possibly be.  Recommend closing this ticket.

**Comment by debjudy** [comment]
Close ticket.
