### ISSUE TITLE
Improve sub-menu styling when in mobile view port 

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#148]
Under https://github.com/GSA-TTS/tts.gsa.gov/issues/118, approach is okay-ish but definitely not ideal.

In order to improve the move experience when in the Join TTS section, I want to improve the handling of sub-menu when in a mobile view port.

**Comment by ximekilgsa** [comment]
PR opened: https://github.com/GSA-TTS/tts.gsa.gov/pull/169
