### ISSUE TITLE
Plan for re-directing existing URLs to new site

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#149]
As https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services is already indexed by search engines, we want to retain as much value as we can from the links - meaning we will want to implement redirects. 

Review existing pages and identify 1:1 to pages on the new site and setup redirects to the new versions.
For pages that don't map 1:1 to the new site, setup redirects to push them to the new site (but not a specific page)
This will be a launch / post-launch activity as we don't want to redirect until new site is live

**Comment by wesley-dean-gsa** [comment]
https://gsa-tts.slack.com/archives/C07BMFCK4NS/p1723042673082639

**Comment by debjudy** [comment]
Duplicate of #158
