### ISSUE TITLE
Request new Slack channel for supporting Talent team

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#152]
https://gsa-tts.slack.com/archives/C07BMFCK4NS/p1723037573176429

maybe #tts-website-support or #tts-website-development-public ?

**Comment by katelandisgsa** [comment]
Let's do #jointts-website-support. I'd like to keep this channel specific to that team. Also upon further reflection, we should probably make it private since they could be discussing topics related to role that aren't ready for public awareness yet.

**Comment by wesley-dean-gsa** [comment]
Kate's going to reach out to Talent and manage that process.
