### ISSUE TITLE
Produce a mapping of pages on the current site to the new site

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#158]
For each page on the [current website](https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services), we'll need to determine where traffic should be directed on the new site.

For example, [18f](https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/18f) and [PIF](https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/the-presidential-innovation-fellows) would both point to the new [people](https://federalist-a2423046-fe43-4e75-a2ef-2651e5e123ca.sites.pages.cloud.gov/preview/gsa-tts/tts.gsa.gov/echo-summer20203/services/people/) page.

**Comment by wesley-dean-gsa** [comment]
The redirects can't be put in place until after the site is launched.

**Comment by wesley-dean-gsa** [comment]
[slack conversation](https://gsa-tts.slack.com/archives/C07BMFCK4NS/p1723477369942579)

**Comment by narumigsa** [comment]
https://docs.google.com/spreadsheets/d/1DPDQ6aF-igSO6NKzYfyzZJn-A0fpEXol1HZcmG5S5Kg/edit?usp=sharing
