### ISSUE TITLE
Prefix or Postfix the webpage titles with the website name

### ISSUE THREAD

**Issue by sknep** [GSA-TTS/tts.gsa.gov#262]
Hey Wes! it's a best practice to use both the site name and the page name in the title attribute of the page. Usually looks something like `"Join Us | tts.gsa.gov"` or `"Join Us | Technology Transformation Services"`. There are a few ways to do this... our cloud.gov site uses the `capture` method to create a title variable in liquid:

https://github.com/cloud-gov/cg-site/blob/0673acf7eafa0746b6fad7463cef5264222d021d/_includes/meta.html#L19

it looks like this is something we also need to address in our eleventy template. I'm sorry I didn't notice it sooner!

**Comment by wesley-dean-gsa** [comment]
https://github.com/GSA-TTS/tts.gsa.gov/blob/main/_includes/meta.html#L19-L23

**Comment by wesley-dean-gsa** [comment]
moving this to blocked while waiting for #284 to be merged

**Comment by wesley-dean-gsa** [comment]
- prefix: Technology Transformation Services | Products
- postfix: Products | Technology Transformation Services

Other than SEO and Search considerations, this is where the pages `<title />` tags appear to the end-user.

![Image](https://github.com/user-attachments/assets/e25e76e5-3cf2-41e5-9bec-7541139c3c37)

**Comment by wesley-dean-gsa** [comment]
per @katelandisgsa's message in [Slack](https://gsa-tts.slack.com/archives/C07BMFCK4NS/p1726602779088229):

> Yes agreed let's do postfix. Thank you!!
