### ISSUE TITLE
Sitemap should use absolute, not relative, URLs

### ISSUE THREAD

**Issue by sknep** [GSA-TTS/tts.gsa.gov#263]
https://tts.gsa.gov/sitemap.xml

These need the baseurl at the start. I'm not sure if that `| absoluteUrl` filter is doing anything for you. I looked and it's in our template too. Maybe it only works if you've loaded the additional package `eleventy-plugin-rss`, where this method is defined?

https://github.com/GSA-TTS/tts.gsa.gov/blob/09a2064bd843a8097359327cbc0e83cdec2e79f7/sitemap.xml.njk#L8

possibly related discussion https://github.com/11ty/eleventy/issues/580

However, there's more than one way to get an absolute URL... you could just dump the `BASEURL` in from the Pages ENV
https://cloud.gov/pages/documentation/env-vars-on-pages-builds/

**Comment by wesley-dean-gsa** [comment]
```
$ grep -r absoluteUrl
sitemap.xml.njk:  {% set absoluteUrl %}{{ page.url | url | absoluteUrl }}{% endset %}
sitemap.xml.njk:    <loc>{{ absoluteUrl }}</loc>
node_modules/@11ty/eleventy-plugin-rss/.eleventy.js:const absoluteUrl = require("./src/absoluteUrl");
node_modules/@11ty/eleventy-plugin-rss/.eleventy.js:  eleventyConfig.addNunjucksFilter("absoluteUrl", absoluteUrl);
node_modules/@11ty/eleventy-plugin-rss/.eleventy.js:module.exports.absoluteUrl = absoluteUrl;
node_modules/@11ty/eleventy-plugin-rss/src/htmlToAbsoluteUrls.js:const absoluteUrl = require("./absoluteUrl");
node_modules/@11ty/eleventy-plugin-rss/src/htmlToAbsoluteUrls.js:      return absoluteUrl(url.trim(), base);
```

like you said, `eleventy-plugin-rss` which is included [here](https://github.com/GSA-TTS/tts.gsa.gov/blob/main/package.json#L33)

**Comment by wesley-dean-gsa** [comment]
https://www.11ty.dev/docs/plugins/rss/#less-important-filters

> Deprecated absoluteUrl: For performance reasons, the [renderTransforms filter](https://www.11ty.dev/docs/filters/render-transforms/) is recommended instead, making use of the HTML <base> plugin. converts a single URL (relative or absolute path) to a full absolute URL including protocol, domain, full path.

**Comment by wesley-dean-gsa** [comment]
`BASEURL` is included in the environment when the site is built.

These folks created a wrapper to set `baseUrl` :
https://github.com/11ty/eleventy/issues/2387#issuecomment-1127527962

Maybe we do something like:

```javascript
if (process.env.BASEURL) {
  baseUrl = process.env.BASEURL;
} else {
  # no idea if this would work or if it's the right syntax
  if (config.getServerOptions()['https']) {
    schema = "https";
  } else {
    schema = "http";
  }
  baseUrl = schema + "://localhost:" + config.getServerOptions()['port'] + "/";
}
```

**Comment by sknep** [comment]
If all you need is a ENV, then you can use a `.env` file for local development that has `BASEURL=localhost:9000` or whatever

**Comment by wesley-dean-gsa** [comment]
https://www.aleksandrhovhannisyan.com/blog/useful-11ty-filters/#4-absolute-urls

```javascript

const BASEURL = process.env.BASEURL ? process.env.BASEURL : 'http://localhost:8080/';

const toAbsoluteUrl = (url) => {
  return new URL(url, BASEURLl).href;
}

config.addFilter('toAbsoluteUrl', toAbsoluteUrl);
```

**Comment by wesley-dean-gsa** [comment]
additional context: we're also looking to bring in the Search API key and Google Analytics ID via environment variables.  Using `.env` is especially tempting for local testing.  It looks like dotenv will work as it populates `process.env` based on the `.env` file (so, if we pass it via an actual environment variable, that'll also show up in `process.env` which is exactly what we want).

I'm not sure why the cited example uses two files and such, but that's likely just my ignorance showing.

**Comment by wesley-dean-gsa** [comment]
https://www.11ty.dev/docs/data-js/#example-exposing-environment-variables

plus that, so...

**Comment by wesley-dean-gsa** [comment]
we're not the only team exploring this exact problem: https://gsa-tts.slack.com/archives/C04823NMA/p1726151335812339

**Comment by wesley-dean-gsa** [comment]
Evidently `BASEURL` is just the path, not the hostname.  At the moment, there is no environment variable for just the hostname.

**Comment by wesley-dean-gsa** [comment]
also, environment variables aren't specific to the deployment model (i.e., there's no way to set a variable to one value for live sites and another value for demo or preview sites)
