### ISSUE TITLE
A lot of meta tags are missing values

### ISSUE THREAD

**Issue by sknep** [GSA-TTS/tts.gsa.gov#264]
https://github.com/GSA-TTS/tts.gsa.gov/blob/09a2064bd843a8097359327cbc0e83cdec2e79f7/_includes/meta.html#L28

are building to:
```html
<meta property="og:title" content="" />
<meta name="description" content="" />
<meta property="og:description" content="" />
```

Perhaps the properties on `page` aren't properly defined? They're empty [in our template too](https://federalist-32bdb3ca-a71a-46e5-ab20-a38ecfdbf143.sites.pages.cloud.gov/preview/cloud-gov/pages-uswds-11ty/dependabot/npm_and_yarn/npm_and_yarn-0b70f2863e/). If I get to this before you do, I'll share the fix.

**Comment by wesley-dean-gsa** [comment]
I'm thinking that we should also put the meta statements inside of a conditional, like:

```Liquid
{% if title && title != "" %}<meta property="og:title" content="{{ title }}" />{% endif %}
```

**Comment by sknep** [comment]
It's *very* bad practice to not have a title for a webpage... it really shouldn't happen. Conditional wrapping makes sense logically, but it's such an unlikely use case that I can't picture making time for it

**Comment by wesley-dean-gsa** [comment]
https://github.com/GSA-TTS/tts.gsa.gov/blob/main/_includes/meta.html#L19-L23

**Comment by wesley-dean-gsa** [comment]
> Conditional wrapping makes sense logically, but it's such an unlikely use case that I can't picture making time for it

yeah, I meant it as an example of conditional wrapping, not that we should not have a title.

By the way, it's kinda funny, that's the one value we actually already wrap 🤣
