### ISSUE TITLE
some join redirects are returning 404s

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#279]
Jim Kreft (Search) wrote:

> btw, some of the [join.tts.gov](http://join.tts.gov/) redirects are landing on 404s, like this one: https://join.tts.gsa.gov/rolling-hiring/

**Comment by wesley-dean-gsa** [comment]
rolling-hiring was removed in #206 ; I just asked him about the source for that link.

**Comment by debjudy** [comment]
Recommendation is to put a re-direct in place to https://tts.gsa.gov/join/hiring-process/

**Comment by wesley-dean-gsa** [comment]
per @katelandisgsa : 

> We could just redirect it to https://tts.gsa.gov/join/hiring-process/. The content was removed altogether so there's not really a relevant redirect

**Comment by wesley-dean-gsa** [comment]
We purged the errant links from Search and reindexed the site so these results aren't showing up anymore.
