### ISSUE TITLE
Remove old info session

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#321]
### URL

https://tts.gsa.gov/join/

### Current Content

Remove from global_info_sessions.yml

[Thursday, September 19th, 2024](https://gsa.zoomgov.com/meeting/register/vJIsc-qhqj0jHl6nkKV8IA7TyuNDlxlHeV8)
12:30-1:30pm ET

(9:30-10:30pm PT)

### Desired Content

Add 

[November 21, 2024](https://gsa.zoomgov.com/webinar/register/WN_xKx0akUhTLClTGto7jmXeQ#/registration) at 12:30pm-1:30pm ET (9:30-10:30am PT)

**Comment by ximekilgsa** [comment]
@debjudy This is also being resolved in my template work, eliminating the need to manually remove past sessions
