### ISSUE TITLE
Address errant display of info session

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#329]
Address why the info session is displaying on https://tts.gsa.gov/join/ when it should not be. 

![image](https://github.com/user-attachments/assets/4dd3a976-cdab-4087-9e23-1b54ace72327)

**Comment by ximekilgsa** [comment]
@debjudy This is being addresses in the template work I'm doing

**Comment by narumigsa** [comment]
It looks like it was resolved, can I close this?
