### ISSUE TITLE
Restore data for salary information

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#341]
We removed the salary lookup table before the launch.  We should return it.

The salary data used to live in `_data/` but I'm not seeing it there any more, so we'll need to find that.

Also, there were locality-based adjustments that made things even more fun.

https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/2024/general-schedule

IIRC from a chat I had with the Talent folks, the General Schedule (Base) applies to most places while the locality pay tables were above (i.e., never below) those base rates.  I also think I remember them saying San Francisco had the largest / highest adjustment.  If that's true, the salary minimum would be for step 1 of the base schedule for a given GS level while the salary maximum would be the step 10 for the San Francisco adjustment for said GS level.

Example, GS-10 would be:
- min: $56,528 (base, step 1)
- max: $106,853 (San Fran, step 10)

The header of the San Jose / San Francisco / Oakland table shows that they have a 45.41% adjustment.  The maths aren't mathing with the interstep deltas; otherwise, I would say start with the base as the min and (base + 10 * delta) * 1.4541 to get the max; unfortunately, that's way too easy.

Therefore, I'm thinking we forget the intestep deltas and include min (base, step 1) and max (base, step 10) and factor in the locality-base adjustment (multiply by 1.4541) as a separate variable.

Anyways...  all of that plus `{{ data.gs.10.min }} - {{ data.gs.10.max * data.gs.locality_adjustment }}` in the job listing template.  :shrug:

**Comment by ximekilgsa** [comment]
Blocked pending decision from talent team re: showing locality adjusted vs base.

**Comment by debjudy** [comment]
https://github.com/18F/join.tts.gsa.gov/blob/main/_data/pay_ranges.yml

**Comment by ximekilgsa** [comment]
PR here: https://github.com/GSA-TTS/tts.gsa.gov/pull/649
