### ISSUE TITLE
job postings closing prematurely

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#361]
> there's a role that is showing closed on the Join TTS and it is still open until 11:59 PM tonight: https://tts.gsa.gov/join/public-experience-contact-center-analyst.html

**Comment by wesley-dean-gsa** [comment]
I'm wondering if the datetime comparison is failing because of the whole 23:59 thing

**Comment by wesley-dean-gsa** [comment]
(to test, try updating the job posting to `2024-09-24 23:59:59` )

https://github.com/GSA-TTS/tts.gsa.gov/blob/main/pages/jointts/positions/PX-Contact%20Center%20Analyst.md?plain=1#L47

**Comment by debjudy** [comment]
Also posting not closing as it should. screen shot is from 8:11am eastern on September 25

`# Put the opening and closing dates of your posting here, if you have them
# These dates MUST be formatted as YYYY-MM-DD, where month and day are 2-digits
opens: 2024-09-13 00:00:00 -0400
closes: 2024-09-24 19:59:59 -0000`

![image](https://github.com/user-attachments/assets/3e78146c-fd14-4358-84bb-8563af537f5d)
