### ISSUE TITLE
info sessions rendering without dates / times on job posting page

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#362]
[Public Experience_ Contact Center Analyst _ Technology Transformation Services.pdf](https://github.com/user-attachments/files/17120759/Public.Experience_.Contact.Center.Analyst._.Technology.Transformation.Services.pdf)

**Comment by ximekilgsa** [comment]
PR here: https://github.com/GSA-TTS/tts.gsa.gov/pull/419
