### ISSUE TITLE
Update PIF info sessions

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#378]
### URL

positions>pif-posting

### Desired Content

Add session for 

Info session: Friday 9/27 at 1:00 - 2:00pm ET
https://gsa.zoomgov.com/webinar/register/WN_UFTZZb0VRyyTDlvPcR-gWw#/registration

**Comment by ximekilgsa** [comment]
@debjudy I think we can close this one!
