### ISSUE TITLE
A11y contrast errors on homepage section

### ISSUE THREAD

**Issue by echappen** [GSA-TTS/tts.gsa.gov#40]
The white paragraph text on grey background for the section underneath the hero area is getting dinged for a11y contrast issues. (Found using the WAVE Chrome plugin.)

![Screen Shot 2022-09-19 at 11 37 22 AM](https://user-images.githubusercontent.com/4267629/191068429-e9b7b87a-a538-46b6-8373-d8901fc52a14.png)

**Comment by wesley-dean-gsa** [comment]
The homepage was updated since this issue was opened.  The WAVE plugin no longer shows any contrast errors (whoo hooo!).

![Screenshot_20240717_095433](https://github.com/user-attachments/assets/59c9f758-ffe7-460f-8bb3-9238ac6dde51)

**Comment by debjudy** [comment]
Approved
