### ISSUE TITLE
Add button / link to the footer to send users to the feedback form

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#417]
This is the link to the feedback form:

https://touchpoints.app.cloud.gov/touchpoints/fc513d86/submit

It should be attached to the bottom of the screen.

Also, the text feedback stuff (medium gray, under Technology Transformation Services, starting with "Tell us about [...]" needs to be removed.  I think this is in `_includes/footer.html` but I could be wrong.

See the mockup provided in a subsequent comment.

**Comment by wesley-dean-gsa** [comment]
Text removed:

![Screenshot_20241001_122315](https://github.com/user-attachments/assets/e7bc8af2-f1e7-4a80-a41a-71f26040ecd3)

**Comment by wesley-dean-gsa** [comment]
it should look like [the touchpoints modal button](https://touchpoints.digital.gov/) which is anchored to the bottom of the page.

![Screenshot_20241001_122449](https://github.com/user-attachments/assets/e329de8c-a18d-4130-9fb8-714dd03ead5f)

**Comment by wesley-dean-gsa** [comment]
The link should point to: https://touchpoints.app.cloud.gov/touchpoints/fc513d86/submit

The link should be anchored to the bottom-right corner of the screen / viewport (not page), just like on the [Touchpoints](https://touchpoints.digital.gov/) homepage.

![Screenshot_20241001_122801_mockup](https://github.com/user-attachments/assets/36e6b002-c79a-4313-9d04-9ca7201240e7)

**Comment by wesley-dean-gsa** [comment]
Added @ximekilgsa as I'm out of my depth with regards to how to make that link work as-desired.

**Comment by ximekilgsa** [comment]
PR: https://github.com/GSA-TTS/tts.gsa.gov/pull/430

**Comment by ximekilgsa** [comment]
@Elysia-Wells Can you take a look at the button [on staging](https://federalist-a2423046-fe43-4e75-a2ef-2651e5e123ca.sites.pages.cloud.gov/preview/gsa-tts/tts.gsa.gov/staging) and let me know if you have any UX/design revisions? TY!
