### ISSUE TITLE
Call to action to sign-up for newsletter on the pages in the Join section

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#428]
As a Talent team member, in order to increase newsletter visibility and sign-ups, I want a call to action to sign-up for newsletter on the pages in the Join section.

+Acceptance criteria+
- Call to action displayed on each page
- Engaging with call to action takes users to newsletter sign-up

Notes
- Slack conversation: https://gsa-tts.slack.com/archives/C07G57Q62E6/p1727893925965509
- Banner should be present on all pages including job postings in the Join section. 
- No changes to banner on home page.  It should remain as it presently is.
- Potential implementation option: It looks like the [homepage's index.html](https://github.com/GSA-TTS/tts.gsa.gov/blob/main/index.html#L19) has a line that pulls in the hero which displays the ["We're hiring" text](https://github.com/GSA-TTS/tts.gsa.gov/blob/main/_includes/hero.html#L5-L17).  We remove the hero reference from the homepage and add it to the site-wide layouts, like [page.html](https://github.com/GSA-TTS/tts.gsa.gov/blob/main/_includes/layouts/page.html)
- Talent team is open to ideas for where to put banner. On one hand stylistically could match the banner that is on the TTS home page or could be located below page headings.  See images
![image](https://github.com/user-attachments/assets/d506c26e-3d85-485d-adb0-7d298a51e0e8)
![image (1)](https://github.com/user-attachments/assets/ae8c529e-2dd1-4d92-a3c2-d86627d10387)

**Comment by ximekilgsa** [comment]
PR here: https://github.com/GSA-TTS/tts.gsa.gov/pull/448
