### ISSUE TITLE
Refactor jobs postings to be based on content in _data

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#455]
Currently, the job postings are represented as Markdown files in [pages/jointts/positions](https://github.com/GSA-TTS/tts.gsa.gov/tree/main/pages/jointts/positions).  These Markdown files start and end with `---` which means they're essentially YAML documents with a `.md` extension.

Because of the `.md` extension:
1. the YAML linting tools aren't linting the `.md` files
2. viewing the files online doesn't provide the benefits (e.g., syntax highlighting) of YAML-aware tooling
3. using tools like schema validators are a challenge as they require an extra step to process the Markdown files and force YAML tooling to run against them

So, an alternative implementation would be to rename the `.md` files to `.yaml` and then update whatever Eleventy site configuration and such needs to be updated so that the `.yaml` files produce HTML in `_site` as-expected.

This approach is very similar to what we're currently doing for services.

[11ty docs on pages from data](https://www.11ty.dev/docs/pages-from-data/)

**Comment by wesley-dean-gsa** [comment]
per #470, please make sure job posting files can be fileglob-matched (e.g., `_data/jobs/*.yaml`)

**Comment by debjudy** [comment]
Needs have evolved and team determined that this ticket is no longer needed.
