### ISSUE TITLE
Adjust header size on cards within Service subpages

### ISSUE THREAD

**Issue by katelandisgsa** [GSA-TTS/tts.gsa.gov#493]
### URL

https://tts.gsa.gov/services/platforms/

### Current Behavior

The header text for all of the pages under Services (Products, Platforms, and People) appears to be larger than before. You can see this where the Citizenscience.gov header is extending beyond the boundary of its card.

### Expected Behavior

The header text should be sized in a way that Citizenscience.gov does not extend beyond the boundaries of the card. This is the longest title we have currently that can't have its text wrap because it is a domain name. If all of the headers are the size that Citizenscience.gov needs to be in order not to extend beyond the boundaries of the card, we won't have issues with any of the titles.

### Steps to Reproduce Behavior

View the Platforms page on desktop.

**Comment by ximekilgsa** [comment]
PR here: https://github.com/GSA-TTS/tts.gsa.gov/pull/542
