### ISSUE TITLE
Info sessions not rendering on mobile 

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#507]
### URL

https://tts.gsa.gov/join/

### Current Behavior

When on mobile device (not mobile view port on computer) the general info sessions box is not displaying info session dates and times. 
![iphone15 plusJoinPage](https://github.com/user-attachments/assets/8202097d-151f-4d44-9a8d-f77098d315e3)

### Expected Behavior

General info sessions will display

### Steps to Reproduce Behavior

Be on mobile device and navigate to tts.gsa.gov/join and scroll to the very bottom of the page.

**Comment by ximekilgsa** [comment]
PR here: https://github.com/GSA-TTS/tts.gsa.gov/pull/535
