### ISSUE TITLE
Conduct accessiblity hueristic review

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#521]
In order to create more accessible site, I want to conduct an accessibility heuristic review.  

Acceptance criteria
- [ ] Report of findings
- [ ] Gather guidelines - link names, header names

**Comment by debjudy** [comment]
https://docs.google.com/spreadsheets/d/1SB39AZACWvjLMJF3cjJn1n3dQ59BXlcGvIc38FS-xvE/edit?gid=0#gid=0

**Comment by ximekilgsa** [comment]
PR here: https://github.com/GSA-TTS/tts.gsa.gov/pull/649
