### ISSUE TITLE
Research USAJOBS API

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#523]
Considerations
* Compliance ATO boundary
* API question.. when would we be interacting with the API?  when the site is built (i.e., from the server) or via JavaScript (i.e., from the client)  Client side
* another API question...  if we're querying an API to determine if the number of applications received has maxed out, could we also just query it to grab the job posting data and render it client-side and not worry about the whole Markdown / YAML thing?

**Comment by debjudy** [comment]
John Jediny from TTS.  

Compliance ATO boundary

**Comment by wesley-dean-gsa** [comment]
Flexion team having a chat today (Tuesday, November 12th) to discuss high-level direction.

**Comment by debjudy** [comment]
Deb, Wes, and Ximena discussed.  While there are 2 technical options that appear feasible, we identified a larger question around the differences between the postings on the TTS side versus those on USAJobs.  So need to clarify with Talent team if it is even worthwhile to pull in content from API.

**Comment by debjudy** [comment]
Ximena and Deb had a conversation with Lauren F about salary ranges where the API came up.  From conversation with Lauren, website team does not think the API makes sense in TTS context, so recommend dropping this item even though it pains us. (We had such high hopes. :sad-face: ) Highlights of items we learned from Lauren

- USAJobs post generally comes after the posting on TTS.
- TTS Talent team is notified by HR when a position is closed.  It doesn't appear that there is an automated way to grab that.
- Writing style between TTS pages and USAJobs are very different so what we potentially could grab is of minimal value.

To support Talent team, we need to look at ways of making the template easier especially the entry of bullets. As we all know, a CMS would make all of this so much easier.  Kate agrees with this direction.
