### ISSUE TITLE
Post a blog

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#678]
In order to promote TTS work and news, I want to be able to post an article to the site. 

*Acceptance criteria*
(x) Read an article

Notes:
* Targeting 2025-01-07 for launch
* Think in terms of blogging functionality
* Access section via link in top navigation. propose "updates" as initial label.
* Blog post fields
Blog post title
Blog post image
Author
Date
Tags
Preview text of the blog post. This preview text should have the ability to be manually specified.
Body text
* Tagging can be manual at first

Non-functional
* Work within USWDS
* Optimize for SEO
* Links for individual posts should be SEO optimized and permanent 
* Include DAP/Google Analytics

Idea writeup: https://docs.google.com/document/d/16c1lbjFW9H_SjB1Rb7fdiTlPR5TNCPWfvPymvs0XYxc/edit?tab=t.0#heading=h.lm7lk2qqy38v

**Comment by ximekilgsa** [comment]
Items needed to unblock!

- Content for first blog, text and image
- Fallback image (for if a blog does not have a featured image)

**Comment by debjudy** [comment]
Development of feature is complete. Closing this issue but not merging code until have first content.
Issue https://github.com/GSA-TTS/tts.gsa.gov/issues/705 tracks work for first article.
