### ISSUE TITLE
On the Jobs page, update sections to reflect live site

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#83]
The Open positions, Upcoming positions, and Find out more sections should be updated to reflect [those on the live site](https://join.tts.gsa.gov/).

**Comment by wesley-dean-gsa** [comment]
Items #84 and #85 were subsumed by this issue.

**Comment by debjudy** [comment]
Need to update the join page to reflect the latest "find out more" information on https://join.tts.gsa.gov/

**Comment by debjudy** [comment]
Will look at actual job postings as we get closer to site launch.  As of 7/30, there are no open positions and two upcoming.  Kate advised not tackling the upcoming yet because there can be tweaks to the postings that are difficult to suss out.

**Comment by wesley-dean-gsa** [comment]
Two of the positions have been ported to the new template leaving two more to convert.

There are a bunch of fields that are specified in the new template that I can't extract from the live postings; these include:

- job post type
- open date
- close date
- weeks open
- contact name
- contact email
- job announcement number
- pd job title
- series
- apply url
- ohrm contact name
- ohrm contact email
- bargaining unit
- promotion potential
- clearance

NOTE: some of the fields are referenced OUTSIDE of the posting template (e.g., `_includes/layouts/jointts/job-updated.html`)

**Comment by wesley-dean-gsa** [comment]
The FedRAMP security director and Login.gov security directory positions are as converted as they can be with the current data.

The PIF and TTS Platforms & Services: Communities & Collaboration Branch Chief roles still need to be converted.

The person who will be able to help is OOO and ought to be back on Monday, August 12th.

**Comment by wesley-dean-gsa** [comment]
The [jobs-updated.html](https://github.com/GSA-TTS/tts.gsa.gov/blob/main/_includes/layouts/jointts/job-updated.html#L32) references a template that doesn't exist, `upcoming_statement.html` that is included when a posting's `state` value is set to `upcoming`.

**Comment by wesley-dean-gsa** [comment]
@katelandisgsa started a [thread in Slack](https://gsa-tts.slack.com/archives/C07G57Q62E6/p1723471185114519) inviting several people from the Talent team to join in the conversation.

**Comment by wesley-dean-gsa** [comment]
See #165 as we're changing the approach from updating the current content (which is old and uses an older template) with the new approach of synchronizing content from the Join TTS repo into this, the TTS website repo.
