### ISSUE TITLE
Dependency update integration tests are failing

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#90]
https://github.com/GSA-TTS/tts.gsa.gov/actions/runs/8924004757/job/24509443244?pr=78
![Screenshot_20240710_113709](https://github.com/user-attachments/assets/e50c60f2-2f3b-4ecc-b5e0-153e5b1720ee)

**Comment by wesley-dean-gsa** [comment]
The underlying issues were #100 (PR #102) and #98 (PR #101); as these have been resolved and the dependency updates now build correctly, this issue can be resolved without further action.

**Comment by wesley-dean-gsa** [comment]
This is an example of a PR running with all of its checks passing.

![Image](https://github.com/user-attachments/assets/daef568f-d38d-4bab-914f-cd41c596f634)

**Comment by debjudy** [comment]
No PR needed. Closing ticket.
