### ISSUE TITLE
CodeQL is passing, but there's no configuration

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#91]
https://github.com/GSA-TTS/tts.gsa.gov/actions/runs/9826781090/job/27128671437

Configuration is organization-wide.

![Screenshot_20240710_114627](https://github.com/user-attachments/assets/854e1f14-49f9-422e-aac9-6ad34504918a)

**Comment by wesley-dean-gsa** [comment]
CodeQL is correctly picking up the JavaScript stuff, so we're good to close this out.

**Comment by wesley-dean-gsa** [comment]
Note the CodeQL workflow returning issues to the Security | Code Scanning tab

![Screenshot_20240805_170446](https://github.com/user-attachments/assets/9edb6b55-c552-4b88-be2b-03d4bc00974d)

**Comment by debjudy** [comment]
No PR needed.  Closing issue.
