### ISSUE TITLE
Pin GHA hashes

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#94]
KICS is complaining about the Snyk GHA not being pinned to a specific hash.

**Comment by wesley-dean-gsa** [comment]
https://github.com/mheap/pin-github-action

**Comment by wesley-dean-gsa** [comment]
https://github.com/GSA-TTS/tts.gsa.gov/security/code-scanning

**Comment by wesley-dean-gsa** [comment]
Going through the workflows as of today (Friday, August 2nd), all of the uses: lines in the workflows are pinned to specific hashes. We can close this ticket out now.

(this was originally (and incorrectly) attributed to #95)

**Comment by debjudy** [comment]
Work completed by other PR. No additional PR.
